/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as DesktopRouteImport } from './routes/desktop'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as ApiMarketsRouteImport } from './routes/api/markets'
import { Route as ApiMemoryRouteImport } from './routes/api/memory'
import { Route as ApiAgentTurnRouteImport } from './routes/api/agent/turn'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiControlClaimRouteImport } from './routes/api/control/claim'
import { Route as ApiControlHeartbeatRouteImport } from './routes/api/control/heartbeat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopRoute = DesktopRouteImport.update({
  id: '/desktop',
  path: '/desktop',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketsRoute = ApiMarketsRouteImport.update({
  id: '/api/markets',
  path: '/api/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryRoute = ApiMemoryRouteImport.update({
  id: '/api/memory',
  path: '/api/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentTurnRoute = ApiAgentTurnRouteImport.update({
  id: '/api/agent/turn',
  path: '/api/agent/turn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiControlClaimRoute = ApiControlClaimRouteImport.update({
  id: '/api/control/claim',
  path: '/api/control/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiControlHeartbeatRoute = ApiControlHeartbeatRouteImport.update({
  id: '/api/control/heartbeat',
  path: '/api/control/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/agents': typeof AgentsRoute
  '/desktop': typeof DesktopRoute
  '/devices': typeof DevicesRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/models': typeof ModelsRoute
  '/plugins': typeof PluginsRoute
  '/skills': typeof SkillsRoute
  '/trade': typeof TradeRoute
  '/api/markets': typeof ApiMarketsRoute
  '/api/memory': typeof ApiMemoryRoute
  '/api/agent/turn': typeof ApiAgentTurnRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/control/claim': typeof ApiControlClaimRoute
  '/api/control/heartbeat': typeof ApiControlHeartbeatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/agents': typeof AgentsRoute
  '/desktop': typeof DesktopRoute
  '/devices': typeof DevicesRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/models': typeof ModelsRoute
  '/plugins': typeof PluginsRoute
  '/skills': typeof SkillsRoute
  '/trade': typeof TradeRoute
  '/api/markets': typeof ApiMarketsRoute
  '/api/memory': typeof ApiMemoryRoute
  '/api/agent/turn': typeof ApiAgentTurnRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/control/claim': typeof ApiControlClaimRoute
  '/api/control/heartbeat': typeof ApiControlHeartbeatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/agents': typeof AgentsRoute
  '/desktop': typeof DesktopRoute
  '/devices': typeof DevicesRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/models': typeof ModelsRoute
  '/plugins': typeof PluginsRoute
  '/skills': typeof SkillsRoute
  '/trade': typeof TradeRoute
  '/api/markets': typeof ApiMarketsRoute
  '/api/memory': typeof ApiMemoryRoute
  '/api/agent/turn': typeof ApiAgentTurnRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/control/claim': typeof ApiControlClaimRoute
  '/api/control/heartbeat': typeof ApiControlHeartbeatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/agents'
    | '/desktop'
    | '/devices'
    | '/login'
    | '/memory'
    | '/models'
    | '/plugins'
    | '/skills'
    | '/trade'
    | '/api/markets'
    | '/api/memory'
    | '/api/agent/turn'
    | '/api/auth/$'
    | '/api/control/claim'
    | '/api/control/heartbeat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/agents'
    | '/desktop'
    | '/devices'
    | '/login'
    | '/memory'
    | '/models'
    | '/plugins'
    | '/skills'
    | '/trade'
    | '/api/markets'
    | '/api/memory'
    | '/api/agent/turn'
    | '/api/auth/$'
    | '/api/control/claim'
    | '/api/control/heartbeat'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/agents'
    | '/desktop'
    | '/devices'
    | '/login'
    | '/memory'
    | '/models'
    | '/plugins'
    | '/skills'
    | '/trade'
    | '/api/markets'
    | '/api/memory'
    | '/api/agent/turn'
    | '/api/auth/$'
    | '/api/control/claim'
    | '/api/control/heartbeat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  AgentsRoute: typeof AgentsRoute
  DesktopRoute: typeof DesktopRoute
  DevicesRoute: typeof DevicesRoute
  LoginRoute: typeof LoginRoute
  MemoryRoute: typeof MemoryRoute
  ModelsRoute: typeof ModelsRoute
  PluginsRoute: typeof PluginsRoute
  SkillsRoute: typeof SkillsRoute
  TradeRoute: typeof TradeRoute
  ApiMarketsRoute: typeof ApiMarketsRoute
  ApiMemoryRoute: typeof ApiMemoryRoute
  ApiAgentTurnRoute: typeof ApiAgentTurnRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiControlClaimRoute: typeof ApiControlClaimRoute
  ApiControlHeartbeatRoute: typeof ApiControlHeartbeatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop': {
      id: '/desktop'
      path: '/desktop'
      fullPath: '/desktop'
      preLoaderRoute: typeof DesktopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/markets': {
      id: '/api/markets'
      path: '/api/markets'
      fullPath: '/api/markets'
      preLoaderRoute: typeof ApiMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory': {
      id: '/api/memory'
      path: '/api/memory'
      fullPath: '/api/memory'
      preLoaderRoute: typeof ApiMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/turn': {
      id: '/api/agent/turn'
      path: '/api/agent/turn'
      fullPath: '/api/agent/turn'
      preLoaderRoute: typeof ApiAgentTurnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/control/claim': {
      id: '/api/control/claim'
      path: '/api/control/claim'
      fullPath: '/api/control/claim'
      preLoaderRoute: typeof ApiControlClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/control/heartbeat': {
      id: '/api/control/heartbeat'
      path: '/api/control/heartbeat'
      fullPath: '/api/control/heartbeat'
      preLoaderRoute: typeof ApiControlHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  AgentsRoute: AgentsRoute,
  DesktopRoute: DesktopRoute,
  DevicesRoute: DevicesRoute,
  LoginRoute: LoginRoute,
  MemoryRoute: MemoryRoute,
  ModelsRoute: ModelsRoute,
  PluginsRoute: PluginsRoute,
  SkillsRoute: SkillsRoute,
  TradeRoute: TradeRoute,
  ApiMarketsRoute: ApiMarketsRoute,
  ApiMemoryRoute: ApiMemoryRoute,
  ApiAgentTurnRoute: ApiAgentTurnRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiControlClaimRoute: ApiControlClaimRoute,
  ApiControlHeartbeatRoute: ApiControlHeartbeatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
